server:
  port: 9987

spring:
  application:
    name: SpringbootFlowManager
  # 服务器配置
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMulQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

flowable:
  # Flowable启动时自动创建和更新数据库表
  database-schema-update: true
  #关闭定时任务JOB
  async-executor-activate: false

# 日志信息
logging:
  level:
    org.flowable: debug
